# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=400, verbose_name='标题')),
                ('article_content', models.TextField(verbose_name='内容')),
                ('article_author', models.CharField(max_length=100, verbose_name='作者')),
                ('article_author_id', models.CharField(max_length=20, verbose_name='作者id')),
                ('article_url', models.URLField(verbose_name='文章地址')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='MStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='股票编码')),
                ('stock_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='股票代码')),
                ('stock_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='股票名称')),
                ('stock_market', models.CharField(blank=True, max_length=10, null=True, verbose_name='所属市场')),
                ('stock_cprice', models.FloatField(blank=True, null=True, verbose_name='当前价格')),
                ('stock_lprice', models.FloatField(blank=True, null=True, verbose_name='昨收价格')),
                ('stock_followers_count', models.IntegerField(blank=True, null=True, verbose_name='关注人数')),
                ('stock_mprice', models.FloatField(blank=True, null=True, verbose_name='最高价格')),
                ('stock_lowprice', models.FloatField(blank=True, null=True, verbose_name='最低价格')),
                ('stock_52mprice', models.FloatField(blank=True, null=True, verbose_name='52周最高价')),
                ('stock_52lowprice', models.FloatField(blank=True, null=True, verbose_name='52周最高价')),
                ('stock_amount_qty', models.FloatField(blank=True, null=True, verbose_name='成交量')),
                ('stock_amount_moneny', models.FloatField(blank=True, null=True, verbose_name='成交额')),
                ('stock_desc', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('stock_business', models.TextField(blank=True, null=True, verbose_name='业务')),
                ('stock_pbv', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('stock_pe', models.FloatField(blank=True, null=True, verbose_name='市净率')),
                ('stock_profit', models.FloatField(blank=True, null=True, verbose_name='每股收益')),
                ('stock_assets', models.FloatField(blank=True, null=True, verbose_name='每股资产')),
                ('stock_dividend', models.FloatField(blank=True, null=True, verbose_name='每股股息')),
                ('stock_stock_marketcapital', models.FloatField(blank=True, null=True, verbose_name='市值')),
                ('stock_change', models.FloatField(blank=True, null=True, verbose_name='涨跌额')),
                ('stock_percent', models.FloatField(blank=True, null=True, verbose_name='涨跌幅')),
                ('stock_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
            },
        ),
        migrations.CreateModel(
            name='MStock_His',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_stock_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='股票编码')),
                ('his_stock_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='股票代码')),
                ('his_stock_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='股票名称')),
                ('his_stock_market', models.CharField(blank=True, max_length=10, null=True, verbose_name='所属市场')),
                ('his_stock_cprice', models.FloatField(blank=True, null=True, verbose_name='当前价格')),
                ('his_stock_lprice', models.FloatField(blank=True, null=True, verbose_name='昨收价格')),
                ('his_stock_followers_count', models.IntegerField(blank=True, null=True, verbose_name='关注人数')),
                ('his_stock_mprice', models.FloatField(blank=True, null=True, verbose_name='最高价格')),
                ('his_stock_lowprice', models.FloatField(blank=True, null=True, verbose_name='最低价格')),
                ('his_stock_52mprice', models.FloatField(blank=True, null=True, verbose_name='52周最高价')),
                ('his_stock_52lowprice', models.FloatField(blank=True, null=True, verbose_name='52周最高价')),
                ('his_stock_amount_qty', models.FloatField(blank=True, null=True, verbose_name='成交量')),
                ('his_stock_amount_moneny', models.FloatField(blank=True, null=True, verbose_name='成交额')),
                ('his_stock_desc', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('his_stock_business', models.TextField(blank=True, null=True, verbose_name='业务')),
                ('his_stock_pbv', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('his_stock_pe', models.FloatField(blank=True, null=True, verbose_name='市净率')),
                ('his_stock_profit', models.FloatField(blank=True, null=True, verbose_name='每股收益')),
                ('his_stock_assets', models.FloatField(blank=True, null=True, verbose_name='每股资产')),
                ('his_stock_dividend', models.FloatField(blank=True, null=True, verbose_name='每股股息')),
                ('his_stock_marketcapital', models.FloatField(blank=True, null=True, verbose_name='市值')),
                ('his_stock_change', models.FloatField(blank=True, null=True, verbose_name='涨跌额')),
                ('his_stock_percent', models.FloatField(blank=True, null=True, verbose_name='涨跌幅')),
                ('his_stock_date', models.DateField(auto_now_add=True, null=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '股票历史',
                'verbose_name_plural': '股票历史',
            },
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='id')),
                ('user_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='名称')),
                ('user_description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='描述')),
                ('user_follower_counts', models.IntegerField(verbose_name='粉丝数')),
                ('user_friends_count', models.IntegerField(verbose_name='关注数')),
                ('user_gender', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='性别')),
                ('user_province', models.CharField(blank=True, max_length=20, null=True, verbose_name='省份')),
                ('user_stocks_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='股票数')),
                ('user_is_deal', models.BooleanField(default=False, verbose_name='是否处理')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
