# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='任务')),
                ('priority', models.IntegerField(choices=[(1, '紧急重要'), (2, '紧急不重要'), (3, '重要不紧急'), (4, '不重要不紧急')], verbose_name='优先级')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('type', models.IntegerField(choices=[(1, '需求管理'), (2, '日常工作'), (3, '数据核对'), (4, '功能验证'), (5, '流程梳理'), (6, '流程梳理'), (7, '其他')], verbose_name='任务类型')),
                ('progress', models.IntegerField(choices=[(1, '未开始'), (2, '需求调研'), (3, '用例整理'), (4, '文档编写'), (5, '文档完成'), (6, '待确认'), (7, '确认完成'), (8, '待开发'), (9, '开发中'), (10, '开发完成'), (11, '需求验证'), (12, '用户验收'), (13, '待上线'), (14, '发布上线'), (15, '完成'), (16, '处理中')], verbose_name='进度')),
                ('checkperson', models.CharField(max_length=20, verbose_name='检查人')),
                ('requestperson', models.CharField(max_length=20, verbose_name='提出人')),
                ('transactor', models.CharField(max_length=20, verbose_name='执行人')),
                ('planstartdate', models.DateField(verbose_name='计划开始日期')),
                ('realstartdate', models.DateField(verbose_name='实际开始日期')),
                ('planenddate', models.DateField(verbose_name='计划完成日期')),
                ('realenddate', models.DateField(verbose_name='实际完成日期')),
                ('relativeperson', models.CharField(max_length=200, verbose_name='关联人')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='任务分析')),
                ('currentobstacles', models.TextField(blank=True, null=True, verbose_name='当前障碍')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='总结')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
