# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='realenddate',
            field=models.DateField(blank=True, null=True, verbose_name='实际完成日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='realstartdate',
            field=models.DateField(blank=True, null=True, verbose_name='实际开始日期'),
        ),
    ]
