# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20171216_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '需求调研'), (3, '用例整理'), (4, '文档编写'), (5, '文档完成'), (6, '待确认'), (7, '确认完成'), (8, '待开发'), (9, '开发中'), (10, '开发完成'), (11, '需求验证'), (12, '用户验收'), (13, '待上线'), (14, '发布上线'), (15, '完成'), (16, '处理中')], default=1, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(verbose_name='进度'),
        ),
    ]
