# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20171219_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='进度'),
        ),
    ]
