# Generated by Django 2.0 on 2017-12-05 06:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, verbose_name='标题')),
                ('blog_author', models.CharField(max_length=100, verbose_name='作者')),
                ('blog_content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('blog_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('blog_createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('blog_views', models.IntegerField(default=1, verbose_name='浏览次数')),
                ('blog_status', models.IntegerField(choices=[(1, '草稿'), (2, '发布'), (3, '作废')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('blog', models.ForeignKey(on_delete=True, to='blog.Blog', verbose_name='博客')),
                ('parent_comm', models.ForeignKey(default=0, on_delete=True, to='blog.Comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='标签'),
        ),
    ]
