# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_createtime',
            field=models.DateTimeField(auto_created=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_views',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
