# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_abstract',
            field=models.TextField(default=1, verbose_name='摘要'),
            preserve_default=False,
        ),
    ]
