# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171115_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
