# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 01:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_abstract',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='摘要'),
        ),
    ]
