# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_status',
            field=models.IntegerField(choices=[(1, '草稿'), (2, '发布'), (3, '作废')], default=1, verbose_name='状态'),
        ),
    ]
