# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excute_time', models.TimeField(verbose_name='运行时间')),
            ],
            options={
                'verbose_name': '执行计划',
                'verbose_name_plural': '执行计划',
            },
        ),
        migrations.CreateModel(
            name='MScheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_start_time', models.DateTimeField(verbose_name='开始时间')),
                ('ms_end_time', models.DateTimeField(verbose_name='结束时间')),
                ('ms_message', models.TextField(verbose_name='日志内容')),
                ('MSche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timertask.MSche')),
            ],
            options={
                'verbose_name': '执行日志',
                'verbose_name_plural': '执行日志',
            },
        ),
        migrations.CreateModel(
            name='MTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名')),
                ('task_desc', models.CharField(max_length=200, verbose_name='任务描述')),
                ('task_createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.AddField(
            model_name='msche',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timertask.MTask'),
        ),
    ]
