# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mschelog',
            old_name='MSche',
            new_name='msche',
        ),
        migrations.AddField(
            model_name='mschelog',
            name='ms_status',
            field=models.TextField(default=2, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
