# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0002_auto_20171116_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msche',
            old_name='excute_time',
            new_name='sche_excute_time',
        ),
        migrations.RemoveField(
            model_name='mschelog',
            name='ms_status',
        ),
        migrations.AddField(
            model_name='msche',
            name='sche_isacive',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='msche',
            name='sche_status',
            field=models.TextField(default=2, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
