# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0003_auto_20171116_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msche',
            name='sche_status',
            field=models.CharField(max_length=20, verbose_name='状态'),
        ),
    ]
