# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0004_auto_20171116_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mschelog',
            name='msche',
        ),
        migrations.AddField(
            model_name='mschelog',
            name='ms_task',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='timertask.MTask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msche',
            name='sche_status',
            field=models.CharField(default='waiting', max_length=20, verbose_name='状态'),
        ),
    ]
