# Generated by Django 2.0 on 2017-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0005_auto_20171116_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msche',
            name='task',
            field=models.ForeignKey(on_delete=True, to='timertask.MTask'),
        ),
        migrations.AlterField(
            model_name='mschelog',
            name='ms_task',
            field=models.ForeignKey(on_delete=True, to='timertask.MTask'),
        ),
    ]
