# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='user_description',
            field=models.TextField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='user_name',
            field=models.CharField(default='', max_length=100, verbose_name='名称'),
        ),
    ]
