# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20171102_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='user_stocks_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='股票数'),
        ),
    ]
