# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_mstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mstock',
            options={'verbose_name': '股票', 'verbose_name_plural': '股票'},
        ),
    ]
