# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20171103_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstock',
            name='stock_business',
            field=models.TextField(blank=True, null=True, verbose_name='业务'),
        ),
    ]
