# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_auto_20171103_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstock',
            name='stock_low_price',
        ),
        migrations.AddField(
            model_name='mstock',
            name='stock_52lowprice',
            field=models.FloatField(blank=True, null=True, verbose_name='52周最高价'),
        ),
        migrations.AddField(
            model_name='mstock',
            name='stock_52mprice',
            field=models.FloatField(blank=True, null=True, verbose_name='52周最高价'),
        ),
        migrations.AddField(
            model_name='mstock',
            name='stock_lowprice',
            field=models.FloatField(blank=True, null=True, verbose_name='最低价格'),
        ),
        migrations.AddField(
            model_name='mstock',
            name='stock_market',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='所属市场'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_amount_moneny',
            field=models.FloatField(blank=True, null=True, verbose_name='成交额'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_amount_qty',
            field=models.FloatField(blank=True, null=True, verbose_name='成交量'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='每股资产'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_cprice',
            field=models.FloatField(blank=True, null=True, verbose_name='当前价格'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_dividend',
            field=models.FloatField(blank=True, null=True, verbose_name='每股股息'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_followers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='关注人数'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_lprice',
            field=models.FloatField(blank=True, null=True, verbose_name='昨收价格'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_mprice',
            field=models.FloatField(blank=True, null=True, verbose_name='最高价格'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_pbv',
            field=models.FloatField(blank=True, null=True, verbose_name='市盈率'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_pe',
            field=models.FloatField(blank=True, null=True, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='mstock',
            name='stock_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='每股收益'),
        ),
    ]
