# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_auto_20171107_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstock',
            name='stock_stock_marketcapital',
            field=models.FloatField(blank=True, null=True, verbose_name='市值'),
        ),
        migrations.AddField(
            model_name='mstock',
            name='stock_symbol',
            field=models.CharField(default=1, max_length=10, verbose_name='股票编码'),
            preserve_default=False,
        ),
    ]
