# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0011_auto_20171107_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstock',
            name='stock_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='股票编码'),
        ),
    ]
