# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0015_auto_20171107_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='MStock_His',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_stock_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='股票编码')),
                ('his_stock_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='股票代码')),
                ('his_stock_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='股票名称')),
                ('his_stock_market', models.CharField(blank=True, max_length=10, null=True, verbose_name='所属市场')),
                ('his_stock_cprice', models.FloatField(blank=True, null=True, verbose_name='当前价格')),
                ('his_stock_lprice', models.FloatField(blank=True, null=True, verbose_name='昨收价格')),
                ('his_stock_followers_count', models.IntegerField(blank=True, null=True, verbose_name='关注人数')),
                ('his_stock_mprice', models.FloatField(blank=True, null=True, verbose_name='最高价格')),
                ('his_stock_lowprice', models.FloatField(blank=True, null=True, verbose_name='最低价格')),
                ('his_stock_52mprice', models.FloatField(blank=True, null=True, verbose_name='52周最高价')),
                ('his_stock_52lowprice', models.FloatField(blank=True, null=True, verbose_name='52周最高价')),
                ('his_stock_amount_qty', models.FloatField(blank=True, null=True, verbose_name='成交量')),
                ('his_stock_amount_moneny', models.FloatField(blank=True, null=True, verbose_name='成交额')),
                ('his_stock_desc', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('his_stock_business', models.TextField(blank=True, null=True, verbose_name='业务')),
                ('his_stock_pbv', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('his_stock_pe', models.FloatField(blank=True, null=True, verbose_name='市净率')),
                ('his_stock_profit', models.FloatField(blank=True, null=True, verbose_name='每股收益')),
                ('his_stock_assets', models.FloatField(blank=True, null=True, verbose_name='每股资产')),
                ('his_stock_dividend', models.FloatField(blank=True, null=True, verbose_name='每股股息')),
                ('his_stock_marketcapital', models.FloatField(blank=True, null=True, verbose_name='市值')),
                ('his_stock_change', models.FloatField(blank=True, null=True, verbose_name='涨跌额')),
                ('his_stock_percent', models.FloatField(blank=True, null=True, verbose_name='涨跌幅')),
                ('his_stock_date', models.DateField(auto_now_add=True, null=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '股票历史',
                'verbose_name_plural': '股票历史',
            },
        ),
    ]
