# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0016_mstock_his'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstock',
            name='stock_update_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
