# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0017_mstock_stock_update_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_createtime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('blog_title', models.CharField(max_length=200, verbose_name='标题')),
                ('blog_author', models.CharField(max_length=100, verbose_name='作者')),
                ('blog_content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('blog_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('blog_views', models.IntegerField(max_length=10, verbose_name='浏览次数')),
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
            },
        ),
    ]
