# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0019_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MArticle',
        ),
        migrations.DeleteModel(
            name='MStock',
        ),
        migrations.DeleteModel(
            name='MStock_His',
        ),
        migrations.DeleteModel(
            name='MUser',
        ),
    ]
